services:
  firewall:
    container_name: firewall
    entrypoint: "tail -f /dev/null"
    image: alpine:latest
    cap_add:
      - NET_ADMIN
    privileged: true
    restart: always
    ports:
      - 99:80
    volumes:
      - ./iptables.sh:/iptables.sh

  alpine_isolated:
    container_name: alpine_isolated
    network_mode: container:firewall
    depends_on: 
      - firewall
    mem_limit: 128m
    image: alpine:latest
    entrypoint: "tail -f /dev/null"

